version: 0.2

env:
  variables:
    APP_RUNNER_SERVICE_ARN: "arn:aws:apprunner:us-east-1:769126752719:service/document-verifier-svc/9c4f9f1ca23645e88553375415ad189b"   # leave empty to skip
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo "No update needed; App Runner auto-deploys prod tag."
  build:
    commands:
      - if [ -n "${APP_RUNNER_SERVICE_ARN}" ]; then aws apprunner start-deployment --service-arn "${APP_RUNNER_SERVICE_ARN}"; else echo "Skipping manual deploy."; fi

artifacts:
  files:
    - imageDetail.json