version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - 'echo "Deploy stage skipped; App Runner auto-deploys the prod tag."'
      - 'exit 0'

artifacts:
  files:
    - imageDetail.json