version: 0.2

env:
  variables:
    IMAGE_NAME: "document-verifier"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_REPO_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-12)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ${IMAGE_NAME}:${COMMIT_SHA} -f app/Dockerfile app
      - docker tag ${IMAGE_NAME}:${COMMIT_SHA} ${ECR_REPO_URI}:${COMMIT_SHA}
      - docker tag ${IMAGE_NAME}:${COMMIT_SHA} ${ECR_REPO_URI}:latest
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push ${ECR_REPO_URI}:${COMMIT_SHA}
      - docker push ${ECR_REPO_URI}:latest
      - printf '{"repository":"%s","tag":"%s"}' "${ECR_REPO_URI}" "${COMMIT_SHA}" > imageDetail.json
artifacts:
  files:
    - imageDetail.json